// Utils
export const REQUEST_LOADING = "REQUEST_LOADING";

// Auth
export const SET_AUTH_LOAD = "SET_AUTH_LOAD";
export const UNSET_AUTH_LOAD = "UNSET_AUTH_LOAD";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Error
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Tours
export const SET_TOUR_LOAD = "SET_TOUR_LOAD";
export const UNSET_TOUR_LOAD = "UNSET_TOUR_LOAD";
export const GET_TOURS = "GET_TOURS";
export const GET_TOUR = "GET_TOUR";
export const ADD_TOUR = "ADD_TOUR";
export const UPDATE_TOUR = "UPDATE_TOUR";
export const DELETE_TOUR = "DELETE_TOUR";

// Reviews
export const GET_REVIEWS = "GET_REVIEWS";
export const GET_CURRENT_USER_REVIEWS = "GET_CURRENT_USER_REVIEWS";
export const UPDATE_CURRENT_USER_REVIEW = "UPDATE_CURRENT_USER_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const DELETE_CURRENT_USER_REVIEW = "DELETE_CURRENT_USER_REVIEW";

// Booking
export const SET_BOOKING_LOAD = "SET_BOOKING_LOAD";
export const UNSET_BOOKING_LOAD = "UNSET_BOOKING_LOAD";
export const SET_CHECKOUT_SESSION_ID = "SET_CHECKOUT_SESSION_ID";
export const SET_CURRENT_USER_BOOKINGS = "SET_CURRENT_USER_BOOKINGS";
export const DELETE_CURRENT_USER_BOOKING = "DELETE_CURRENT_USER_BOOKING";

// Users
export const SET_USER_LOAD = "SET_USER_LOAD";
export const UNSET_USER_LOAD = "UNSET_USER_LOAD";
export const GET_GUIDES = "GET_GUIDES";
export const GET_USERS = "GET_USERS";
